### ISSUE TITLE
Transform tool: ability to rotate/scale a selection

### ISSUE THREAD

**Issue by blurymind** [dalboris/vpaint#28]
Rotating a selection is important because a big part of movement is based on rotating joints that cause arcs.
 I hope is manages to get in 1.6 :)

**Comment by dalboris** [comment]
The feature is now implemented and will be part of VPaint 1.6.

Though, the interpolation in time is still linear for now, so it doesn't create an arc motion. This is because once rotated, the algorithm computing the motion from the keyframes is not that you created the keyframe by rotating another keyframe (e.g., the same keyframe could have been created via sculpting, following a linear path). This will be fixed when I'll implement a smarter, non-linear interpolation algorithm, but that's complicated and will take some time.
