### ISSUE TITLE
Compile instructions

### ISSUE THREAD

**Issue by sobkas** [dalboris/vpaint#3]
It's so much easier to compile it using qmake and make than use qtcreator:
qmake src/VPaint.pro
#make sure qmake is from qt5
make

**Comment by norpol** [comment]
Works for me, on Debian I had only to install the package `qt5-default`.

**Comment by scribblemaniac** [comment]
A couple things to note here:
- Running make will fill the current working directory up with a bunch of compiled classes. This is generally not something you want to do in the main directory, so I would suggest making a build folder and from that directory running `qmake ../src/VPaint.pro` rather than `qmake src/VPaint.pro`
- Mac users still have a more involved process even with your suggestion. They still have to make a custom mkspec as described in the readme and will have to add the `-spec <mspec_name>` option to their qmake command.
- Saying that one way is easier than the other is a matter of opinion. Some people (likely those with little to no command line experience) may find it easier to use qt creator.

**Comment by dalboris** [comment]
Yes, I did use command line compilation before, but at the end of the day, using Qt Creator was what was giving me the best homogeneous experience across platforms, and Qt Creator does a good job out of the box to separate object files to source with the "shadow build", without having to do it myself in the .pro file. :-)

**Comment by blurymind** [comment]
I will make a build script for arch linux/manjaro for AUR later on

**Comment by scribblemaniac** [comment]
@blurymind I don't have any experience with arch linux, but [these](https://aur.archlinux.org/packages/?K=vpaint) kind of sound like what you are planning on making.

**Comment by blurymind** [comment]
Wow! Someone beat me to it eheheh xD
Glad to see that vpaint is spreading like wild fire

**Comment by TheNiceGuy** [comment]
I did, I'm the maintainer! If there's something wrong with the AUR package, feel free to send me the appropriate changes. :)

**Comment by sobkas** [comment]
I think that adding qmak && make as an alternative to qtcreator build process will make lives of many people easier. Like for example mine. When I tried to compile it using qtcreator I couldn't make it to do anything. Only using qmake and make showed any useful errors.
Thanks.

**Comment by scribblemaniac** [comment]
Qt Creator is capable of showing the exact same output as you would see with qmake. You simply have to go to the compile output tab.

**Comment by dalboris** [comment]
Wow, you guys are blazingly fast. Thx TheNiceGuy for the AUR package! 

I can add later the command line instructions if you want, it doesn't hurt. But indeed it's pretty much equivalent as what Qt Creator does, except it's gonna pollute your source code by object files as of now.
