### ISSUE TITLE
Negative frames aren't visible on timeline

### ISSUE THREAD

**Issue by wraybowling** [dalboris/vpaint#37]
![screen shot 2015-09-09 at 3 53 54 pm](https://cloud.githubusercontent.com/assets/1120619/9772596/324cff38-570b-11e5-8130-7b5a7c6ecda4.png)

**Comment by dalboris** [comment]
You can scroll the timeline with the middle mouse button. Agreed, this is not documented anywhere yet, sorry about that :-/

**Comment by wraybowling** [comment]
![mb829_av1](https://cloud.githubusercontent.com/assets/1120619/9791061/4404a7f2-57a7-11e5-8e6d-fa884ea7b625.jpg)

In that case, I suggest you take a look at Blender where holding Alt simulates the middle mouse button.

**Comment by dalboris** [comment]
Ha! I suggest to implement a mouse-detection function and display a popup warning users not to use such crappy mice :-P More seriously, yes, I'll have to see how to provide workarounds to best serve users without middle click, but I think I will keep design decisions based on three-button mice (anyone in animation has a three-button mouse and it allows for much better workflow, and even Wacom users have three "buttons": the pen as left click, and two side buttons for middle click and right click)

**Comment by Emasoft** [comment]
Some rules for good UI design:
- A good user interface should never assume more than one mouse and one button (or one touch/one pen tap). Any other additional button, shortcut or key combination that the user can learn should always be a secondary shortcut for advanced users, to learn with time. 
- A good user interface should never force the user to remember anything. Icons should always be accompanied with labels, shortcuts for menu commands should always be displayed in the menus, and pressing modifiers keys (ALT, CTRL, CMD, Win, etc) should always display the list of alternative actions or effects of clicking or pressing other keys while those modifiers are active.
- A good user interface does not fill the screen with options, but only display the options and the actions that the user can do on the currently selected elements.
- Always add a treeview list of all elements in the document, because selecting objects is the most frequent operation and the best way to do it is from a list of named elements sorted by z value or layer.  Always allows to filter-search such a list, using both elements names and elements properties, and always allow multiple selections and custom grouping for quick selection.
- A good user interface never make the user to guess the effect of changing a numerical value or of apply an action. It always shows the live preview before apply it. If the user have to ask what is a button for or what an option does, then you have already failed.
- Help or docs are abominations for the good designer. Use hinting and contextual popups for everything. If the user needs an help or a manual to understand your app, you have already failed.
- Thou shalt have an infinite undo/redo history, and thou shalt save it with the project.

**Comment by dalboris** [comment]
Thanks, always good to keep good UI design guidelines in mind. Though, note that I have taken an HCI class at graduate level, so I have academic training in interface design. :-) I'd just like to remind one the the most important guideline of all: « there are no rules, just guidelines. ». Which means it is important to remember that not every guideline apply to every design problem. For instance, "a good user interface should never assume more than one mouse and one button.": this is definitely an application-dependent guideline, and more specifically an Apple guideline which I don't think every designer agrees with. If 99% of your user base has at least two buttons, then you should definitely leverage them if it allows for a much more efficient workflow. Of course, whenever there are simple alternative using only one button, it should be preferred.

**Comment by scribblemaniac** [comment]
In my opinion, you are looking at it completely wrong. Yes your interface should aim for a more efficient workflow, and yes it should take into consideration what assumptions you are making about the user. However it is far more important that things be configurable. That way people that can't use the default interface (because of a missing mouse button for example) can easily reconfigure it to work with their system. Also those who are unsatisfied with the efficiency of the workflow can fine-tune it to their specific tastes. The ability for users to easily configure their environment the way they want it will result in a program that better suits more of your users than even the most carefully designed static interface.

**Comment by dalboris** [comment]
Well, yes of course, I am totally in favour of things to be configurable!
