### ISSUE TITLE
Timeline stepping not bounded

### ISSUE THREAD

**Issue by lablanu** [dalboris/vpaint#49]
I'm not sure if this is wanted behavior, but stepping to next and previous frames can go in both directions infinitely.
I suggest bounding at least the negative end, adding a check to lines like https://github.com/dalboris/vpaint/blob/master/src/Gui/Timeline.cpp#L1030

**Comment by dalboris** [comment]
Thx for the report! This is the intended behaviour, and I'd personally 
prefer to keep it as the default. Though, since it is primarily a matter of 
taste, I suggest to add it as a user preference setting, when user 
preferences are eventually implemented in VPaint.

**Comment by scribblemaniac** [comment]
Sorry I'm a little late to this conversation, I was unable to access github this past weekend.

#4 and #15 are relevant here so I just wanted to mention them so it's all linked. To reiterate a point briefly mentioned in the latter that you may be interested to know, the code for 3 different timeline behaviors have already been coded and are just commented out at the moment. Due to this fact, when a proper user preferences dialog is made, this will be among the first options implemented. If you can't wait until then, you can comment out the current implementation and uncomment the implementation you desire. You will have to compile VPaint yourself however, which can be difficult depending on if your level of programming experience.
