### ISSUE TITLE
Checking for updates

### ISSUE THREAD

**Issue by scribblemaniac** [dalboris/vpaint#52]
Good to see some activity here! Anyway, I was wondering if having VPaint check for updates in the background is something you would be interested in.

It should be pretty straightforward to implement. Just download [Github's release feed for this project](https://github.com/dalboris/vpaint/releases.atom), parse it to find the latest tag, and then compare version numbers. VPaint already has XML parsing, so that makes it even easier.

If this is something you are interested in, let me know and assign this issue to me, I should have the time to do it soon since I've just finished up a larger project :smile:

**Comment by dalboris** [comment]
Hi there! Yes, I'd be definitely interested in that :-) If you're interested to do it, go ahead!

Some suggestions on the top of my head, feel free to comment or propose something better.

* Instead of using the github release feed, it would be even simpler to just download a super-duper simple file from vpaint.org removing any need for parsing. I just created one here: 
http://vpaint.org/latestversion

* This also allows to have better control on when the notice is sent: I'd rather first have it available on github, then add the download link and updated info on vpaint.org, then make a sanity check that things are working, and only then update the http://vpaint.org/latestversion file (and send an email to mailing list, announce it on social media, etc.). All of these should ideally be scripted to be done all at once, but it's a bit overkill for now.

* For testing the behaviour, some alternative files with different version numbers:
http://vpaint.org/latestversion16
http://vpaint.org/latestversion20

* Checking itself is gonna be indeed easy, but what is likely to take the most time is the Gui for the notification, in case there's indeed a new version available. Obviously a popup with the download link of the new version, but it'd be nice if you have time to have several options: "Download now", "Remind me next time", or "Stop checking for updates", the latter requiring to write in VPaint settings.

* The download link depends on which platform you're in. I'll make sure to follow the same naming convention:
Windows: https://github.com/dalboris/vpaint/releases/download/v1.5/VPaint.1.5.Setup.msi
MacOS X: https://github.com/dalboris/vpaint/releases/download/v1.5/vpaint.dmg
Linux: Just point to https://github.com/dalboris/vpaint/releases for now (in the future, we should make deb/rpm packages for the major distribs, detect which distrib is used, and send the corresponding link, but that's gonna take some time and is probably not worth doing yet)

Thanks!

**Comment by dalboris** [comment]
(important note since you're active here: VPaint files from 1.5 can't currently be opened. I'll continue to do file format breaking changes in the coming 2/3 days, then write a converter from 1.5 files to 1.6 files, so wait for a week or so before trying to open files from a build from master)

**Comment by scribblemaniac** [comment]
The suggestion for using that url at vpaint.org is a good one. I will be sure to do that.

As for the download link, don't you think you could have it point to the tar.gz file for linux? If someone is using linux, there is a very good chance they know what to do with that.

Thanks for the note, I just compiled the latest code, which means I probably would've opened up some of my vec files today if you had not told me this. What kind of changes are you making that would break compatibility?

**Comment by scribblemaniac** [comment]
Also, when should I check for updates. I was planning on just running a check on startup, is that good enough for you?

**Comment by dalboris** [comment]
Yep, run on startup, that'd be what I would do.

I don't have a strong opinion for linux users, but I feel it's slightly better to point to https://github.com/dalboris/vpaint/releases as there might be more pre-built packages which would be more convenient for some. Somebody who wants to compile himself can always download the tar.gz source from there.

Breaking compatibility changes: 
 * All cells (vertex, edge, etc...) become children of an XML elements "objects"
 * CSS "style" attributes becomes direct XML attributes (i.e., I drop the CSS syntax, and style="color:rgba(0,0,0,1)" becomes color="rgba(0,0,0,1)" ).
 * canvas "left+top" becomes canvas "position" 
 * canvas "width+height" becomes canvas "size"
 * playback "firstframe+lastframe" becomes "framerange"
 * curve="xyw-dense: 5 474.5,66.5,51.6212463329176 ..." becomes curve="xywdense(5 474.5,66.5,51.6212463329176 ...)"

Only the first one is implemented yet. But that will be transparent for users using the stable versions as I will detect if it's the old format and convert automatically. It's just in a temporary state in master for now (but you can always save then load with the same build at any commit, that works).

**Comment by dalboris** [comment]
By the way, are you open for chatting? I just see the existence of https://gitter.im/, have you used it before? I'm considering trying and adopting for VPaint, it seems a good communication platform. Otherwise we can use GTalk.

**Comment by scribblemaniac** [comment]
I've heard of gitter before, but this is the first time I've taken a close look at it. It seems like it would work well and I would be willing to try it out if you set something up for VPaint.

**Comment by dalboris** [comment]
Ok, setting up something now.

**Comment by scribblemaniac** [comment]
Okay, I have to go right away, but I'll probably be able to check it out in about 5 hours.

**Comment by dalboris** [comment]
Ok, that's fine, I created a room for the vpaint repo and written one message, try to reply when you get some time :)
