### ISSUE TITLE
Update roadmap timeline

### ISSUE THREAD

**Issue by scribblemaniac** [dalboris/vpaint#63]
@dalboris Can you please update the expected dates on the roadmap? I'm not rushing your or anything like that, I just want to know where we're at, and in particular how long you expect before the 1.8 release so that I can get the importer and maybe a couple other things done in time.

**Comment by dalboris** [comment]
Hi @scribblemaniac ! Yes, thanks for the note, I should have done that a long time ago. I have largely underestimated the time to do the rewrite. Also, I actually decided to rewrite more than I initially planned, despite the delay, because it has to be done eventually and I'm not sure I'll ever have a better opportunity to do it.

I updated the roadmap to something more realistic, according to what I currently know. I liked the previous roadmap better, but well...

The good news is, you definitely have time before 1.8 ;-)

**Comment by scribblemaniac** [comment]
> The good news is, you definitely have time before 1.8 ;-)

Haha, no kidding! Well I have no problem with you rewriting more of it. It would take longer to rewrite things once there are more features in place, so in the long run you're probably saving time!

**Comment by dalboris** [comment]
Yes :-)
