### ISSUE TITLE
Z view option

### ISSUE THREAD

**Issue by hollunder** [dalboris/vpaint#78]
Hi,

I was thinking that it would be very useful to have a per Z level view option.
That would show only objects at the given Z level, so you could easily see what is below/above what.
You could add something similar to onion skinning to that.
It would greatly increase your ability to see what goes on in even moderately complex animations.

**Comment by dalboris** [comment]
In fact, every cell (i.e., every vertex, every edge, and every face) is at its own Z-level. More specifically, there is in fact no z "value", I simply keep track of a global ordering of cells. So that means that you would only see a single cell with such option, which is not very useful.

However, what could be done is an option to display all the cells between two given cells. I'm not sure how useful and intuitive to use that could be though. Any thoughts?

Note: in the future, I plan to implements layers, which is I think a better alternative to the functionality you are looking for, so maybe it's better just to wait to have layers, and see if this fills your need.

**Comment by hollunder** [comment]
Thanks for the explanation.
Yes, I think that layers is the traditional approach here and that may well work.
