### ISSUE TITLE
Crash on opening converted .vec

### ISSUE THREAD

**Issue by hollunder** [dalboris/vpaint#83]
This is also not important currently, but nevertheless...

1. Take the rhino.vec file from here: http://www.vpaint.org/forum/viewtopic.php?f=6&t=60
2. Try to open it, let Vpaint convert it to the new format.
3. crash.
[rhino.vec.zip](https://github.com/dalboris/vpaint/files/720303/rhino.vec.zip)

**Comment by hollunder** [comment]
oversize and transparent.rar from here shows nothing: http://www.vpaint.org/forum/download/file.php?id=9

I would have liked to see how this was actually done. There are a lot of very interesting things on the forum, mostly "lost" to the old version.

**Comment by dalboris** [comment]
In fact, this wasn't caused by an error with the conversion, but by the fact that there were empty inbetween faces in the file, which VPaint 1.5 seemed to be able to handle, but 1.6 crashed on opening.

Here is the converted file with the offending inbetween faces manually deleted (they aren't visible anyway). You should be able to open this in VPaint 1.6: 

[rhino.vec.zip](https://github.com/dalboris/vpaint/files/3853571/rhino.vec.zip)

I've also added a fix to VPaint so that VPaint 1.7 will now be able to directly open the automatically converted file including the offending inbetween faces.

Unfortunately, I'm afraid this Rhino file might be less interesting than you hoped: while a super cool example, it's drawn frame by frame, without inbetween cells, and the inbetween faces seem to have been created by mistake.

The files "oversize and transparent" were unfortunately created with VPaint 1.0 with a custom file format which wasn't even XML, and can't be automatically converted :( I can't even open it on this computer as I have neither a binary of VPaint 1.0 neither the source (it wasn't open source yet, and I didn't include earlier source history in GitHub, since the history included other stuff which I didn't want to open source). I can probably find it in some hard drive somewhere but I'd have to dig it up.
