### ISSUE TITLE
Weird edge inbetween

### ISSUE THREAD

**Issue by hollunder** [dalboris/vpaint#84]
I created a simple walk"cycle" with three keyframes using motionpaste. It's not a real walkcycle because just by using motionpaste I can not arrive at exactly with what I started with.

So far so good. I did this with very few frames however and tried to manually scale this using a very stupid method: inbetween piece-by-piece. This seems to be pretty much the only way inbetween works. The most complex shape I found working was a closed edge with multiple vertices.

Tedious, but it mostly work, safe for one weird artifact. The hand of my little stick man got detached and re-attached the other way around. I found this interesting, i think this is a bug. See attached file.

[walkcycle2.vec.zip](https://github.com/dalboris/vpaint/files/720399/walkcycle2.vec.zip)

**Comment by dalboris** [comment]
Hi @hollunder, sorry about not looking at this sooner! The reason this occurs is that when inbetweening from one key edge "AB" to one key edge "CD", there are basically two possibilities: either B is mapped to C, or it is mapped to D:

![image](https://user-images.githubusercontent.com/4809739/71039910-9b3a0980-2125-11ea-9069-7070e319b9dc.png)

Currently, VPaint only uses the angle between the two edges to decide: if angle(AB, CD) is smaller than angle(AB, DC), then VPaint chooses to map A to C, which is what happens here (AB and CD are almost perpendicular, but in fact the arm rotation is slightly more than 90 degrees).

When VPaint gets it wrong like that, you can do the following:
1. Undo
2. Go to View > Advanced > Advanced Settings, and check "inverse direction"
3. Try again, this time VPaint will pick the other direction
4. Uncheck "inverse direction"

![image](https://user-images.githubusercontent.com/4809739/71040374-c1ac7480-2126-11ea-9b9c-34d3b157cc65.png)

Currently, the interface for doing this is quite clunky, I agree. It would be better for example to have a shortcut that would invert the direction of the last created edge inbetween, for example. Or some way to explicitly tell VPaint the direction before inbetweening. Or some popup to ask the user when VPaint detects that the situation is a bit ambiguous (e.g., edges almost perpendicular).

We could also make VPaint smarter so that it guesses right in the first place: in this specific case, the topological information makes it quite clear which direction should be chosen, regardless of the geometrical angle between the edges. Having access to this topological info is actually one of the potential strength of VPaint data structure, and it's a shame it isn't leveraged here!

All of these things are non-trivial to design and/or implement, so I don't think I will add them to VPaint.   However, this is part of the improvements that I wish to implement in VGC Animation.
