### ISSUE TITLE
Layers white color background.

### ISSUE THREAD

**Issue by ebarranco** [dalboris/vpaint#93]
I only use dark themes for working and the new feature has a white background color that doesn't behave like the rest of vpaint, and I can't read my layers using any dark theme.

I try to explain better [in this video.](https://www.dropbox.com/s/5uxyn4zksm6nw1j/2018-11-18%2016-48-16.mov?dl=0)

**Comment by dalboris** [comment]
Hey @ebarranco, just curious, which Linux distro + version of Qt do you use to compile VPaint, and how exactly do you compile and run the program (via QtCreator, command-line, etc...)?

Because I'm on Kubuntu 18.04, and when I change the color scheme in the KDE Settings, I have to restart VPaint to see the changes, while in other apps (Settings, Dolphin) the changes are applied instantly, and I see that in your video the changes are applied instantly to VPaint too.

I compile through Qt Creator (I don't think this matters), and compiling against either Qt 5.6.2 or Qt 5.11.1, and running VPaint either via Qt Creator or via the command-line (`./Gui/VPaint`), I can't get the color scheme to be applied instantly to VPaint like you do.

This, of course, is an independent issue than the white background.

**Comment by dalboris** [comment]
Alright, this should be now fixed :)

![vpaint-layers-color-scheme](https://user-images.githubusercontent.com/4809739/48702402-224e4280-ebf1-11e8-8498-6d5d3070c969.png)

**Comment by ebarranco** [comment]
Thanks @dalboris ! Yeap it works. 
I'm  on Linux 4.19.1-1 Manjaro (18.0) KDE Edition, plasmashell 5.14.3, QMake version 3.1 Using Qt version 5.11.2 in /usr/lib.  I build from [vpaint-git ](https://aur.archlinux.org/packages/vpaint-git/)in arch repositories

**Comment by dalboris** [comment]
Thanks @ebarranco for the additional info. Ok, I'll just assume that Manjaro handles things a bit differently than Kubuntu then.
